<?xml version="1.0" encoding="utf-8"?><Database Name="COLOC@R" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCALHOST\SQLEXPRESS;Initial Catalog=COLOC@R;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="COLOC_RConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AuthToken" Member="AuthTokens">
    <Type Name="AuthToken">
      <Column Name="token" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ipAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="lastActivity" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fullyAuthAndOnline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_AuthToken" Member="User" ThisKey="idUser" OtherKey="idUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loginUser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="emailUser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="passwordUser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="avatarUser" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="firstNameUser" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="lastNameUser" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="birthdayUser" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="registeredDateUser" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lastConnectionUser" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_AuthToken" Member="AuthTokens" ThisKey="idUser" OtherKey="idUser" Type="AuthToken" />
      <Association Name="User_Profile" Member="Profiles" ThisKey="idUser" OtherKey="idUser" Type="Profile" />
    </Type>
  </Table>
  <Table Name="dbo.criteria_Cities" Member="criteria_Cities">
    <Type Name="criteria_City">
      <Column Name="idCity" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codeCity" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="libelleCity" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="criteria_City_Profile" Member="Profiles" ThisKey="idCity" OtherKey="cityColoc" Type="Profile" />
      <Association Name="criteria_City_Profile1" Member="Profiles1" ThisKey="idCity" OtherKey="cityOrigin" Type="Profile" />
    </Type>
  </Table>
  <Table Name="dbo.criteria_DomainsStudies" Member="criteria_DomainsStudies">
    <Type Name="criteria_DomainsStudy">
      <Column Name="idDomainStudies" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="libelleDomainStudies" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="criteria_DomainsStudy_Profile" Member="Profiles" ThisKey="idDomainStudies" OtherKey="domainStudies" Type="Profile" />
    </Type>
  </Table>
  <Table Name="dbo.Profiles" Member="Profiles">
    <Type Name="Profile">
      <Column Name="idProfile" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cityOrigin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cityColoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="yearStudies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="domainStudies" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="criteria_City_Profile" Member="criteria_City" ThisKey="cityColoc" OtherKey="idCity" Type="criteria_City" IsForeignKey="true" />
      <Association Name="criteria_City_Profile1" Member="criteria_City1" ThisKey="cityOrigin" OtherKey="idCity" Type="criteria_City" IsForeignKey="true" />
      <Association Name="criteria_DomainsStudy_Profile" Member="criteria_DomainsStudy" ThisKey="domainStudies" OtherKey="idDomainStudies" Type="criteria_DomainsStudy" IsForeignKey="true" />
      <Association Name="User_Profile" Member="User" ThisKey="idUser" OtherKey="idUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>