<?xml version="1.0" encoding="utf-8"?><Database Name="COLOC@R" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCALHOST\SQLEXPRESS;Initial Catalog=COLOC@R;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="COLOC_RConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AuthToken" Member="AuthTokens">
    <Type Name="AuthToken">
      <Column Name="token" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ipAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="lastActivity" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fullyAuthAndOnline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_AuthToken" Member="User" ThisKey="idUser" OtherKey="idUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="idCity" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codeCity" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="libelleCity" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="City_User" Member="Users" ThisKey="idCity" OtherKey="city" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loginUser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="emailUser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="passwordUser" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="firstNameUser" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="lastNameUser" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="type" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priceColoc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descUser" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="m2Coloc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastConnectionUser" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_AuthToken" Member="AuthTokens" ThisKey="idUser" OtherKey="idUser" Type="AuthToken" />
      <Association Name="City_User" Member="City1" ThisKey="city" OtherKey="idCity" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
</Database>